export const customersHeader = [
  "ID",
  "userName",
  "email",
  "phoneNumber",
  "totalOrders",
  "totalSpending",
  "location",
  "actions",
];
export const customers = [
  {
    ID: 0,
    userName: "Zahra Mirzaei",
    email: "zahra_mirzaei@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 804,
    totalSpend: "$120.00",
    location: "UK",
  },
  {
    ID: 1,
    userName: "John Smith",
    email: "john_smith@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 230,
    totalSpend: "$120.00",
    location: "UK",
  },
  {
    ID: 2,
    userName: "Kyle Simpson",
    email: "Kyle_simpson@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 120,
    totalSpend: "$120.00",
    location: "USA",
  },
  {
    ID: 3,
    userName: "	Maximilian Doe",
    email: "john_smith@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 15,
    totalSpend: "$120.00",
    location: "USA",
  },
  {
    ID: 4,
    userName: "John Smith",
    email: "john_smith@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 270,
    totalSpend: "$120.00",
    location: "USA",
  },
  {
    ID: 5,
    userName: "John Smith",
    email: "john_smith@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 310,
    totalSpend: "$120.00",
    location: "USA",
  },
  {
    ID: 6,
    userName: "John Smith",
    email: "john_smith@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 804,
    totalSpend: "$120.00",
    location: "USA",
  },
  {
    ID: 7,
    userName: "Andrei Neagoie",
    email: "john_smith@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 803,
    totalSpend: "$120.00",
    location: "USA",
  },
  {
    ID: 8,
    userName: "John Smith",
    email: "john_smith@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 110,
    totalSpend: "$120.00",
    location: "USA",
  },
  {
    ID: 9,
    userName: "John Smith",
    email: "john_smith@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 804,
    totalSpend: "$120.00",
    location: "USA",
  },
  {
    ID: 10,
    userName: "Jason Bourne",
    email: "test@gmail.com",
    phoneNumber: "+98 918 123 45 67",
    totalOrders: 460,
    totalSpend: "$260.00",
    location: "UK",
  },
];

export const productsHeader = [
  "ID",
  "product",
  "inventory",
  "price",
  "category",
  "actions",
];
export const products = [
  {
    ID: 0,
    product: "Apple AirPods",
    inventory: 30,
    price: "$200.00",
    category: "digital",
  },
  {
    ID: 1,
    product: "NUBWO G06",
    inventory: 28,
    price: "$120.00",
    category: "digital",
  },
  {
    ID: 2,
    product: "Hooded Sweatshirt",
    inventory: 10,
    price: "$10.00",
    category: "clothing",
  },
  {
    ID: 3,
    product: "Keyboard",
    inventory: 50,
    price: "$50.00",
    category: "digital",
  },
  {
    ID: 4,
    product: "T-Shirt",
    inventory: 20,
    price: "$75.00",
    category: "clothing",
  },
  {
    ID: 5,
    product: "LED Monitor",
    inventory: 31,
    price: "$510.00",
    category: "digital",
  },
  {
    ID: 6,
    product: "Socks",
    inventory: 5,
    price: "$10.00",
    category: "clothing",
  },
  {
    ID: 7,
    product: "Mouse",
    inventory: 3,
    price: "$16.00",
    category: "digital",
  },
  {
    ID: 8,
    product: "Mielle",
    inventory: 36,
    price: "$170.00",
    category: "beauty",
  },
  {
    ID: 9,
    product: "hat cap",
    inventory: 17,
    price: "$25.00",
    category: "clothing",
  },
  {
    ID: 10,
    product: "CeraVe",
    inventory: 7,
    price: "$220.00",
    category: "beauty",
  },
  {
    ID: 11,
    product: "Neutrogena",
    inventory: 30,
    price: "$205.00",
    category: "beauty",
  },
];
